### PR TITLE
set password hash

### PR DESCRIPTION
**Pull request by TheAlgorythm**
#458

### CODE REVIEW

**Comment by grooverdan** [comment]
Good start, thanks. I made the following changes (which are pushed onto your github fork):
* used tabs instead of space indents for consistency
* `./update.sh` updates the other subdirectories based on the top level file you changed.
* added test case
* `rootCreate` seemed to have moved location and might have been incorrect, which I think it was before too.
* added few more incompatibility checks
* `if [ a ] && ( [ b ] || [ c ])` does subshell things. As I understand it `&&` and `||` are equal precidence, so `b || c && a` is equal to `( b || c)) && a`.

TODO:

* check test failures `.test/run.sh {image} [{testname}]`
* alter to support `MARIADB_PASSWORD_HASH_FILE` and  `MARIADB_ROOT_PASSWORD_HASH_FILE`.

**Comment by TheAlgorythm** [comment]
Somehow `./update.sh` doesn't work on my machine:

```
update.sh: line 8: 10.3: syntax error: invalid arithmetic operator (error token is ".3")
update.sh: line 10: focal: unbound variable
```

**Comment by TheAlgorythm** [comment]
I am not sure if I will be able to understand the test failures as I am neither a Docker nor a Bash expert.

**Comment by TheAlgorythm** [comment]
This seems to be a CI problem and not related to my changes as they are also on the MAIN branch.
I think that all should be done, besides a new `./update.sh` run (see above).

**Comment by grooverdan** [comment]
Thanks for trying it out and testing it some more. I'll take it from here and get this finished.

Thanks for describing the update.sh portability issues on MacOS, I'll see if I can correct these.

**Comment by grooverdan** [comment]
no idea about the CI failures. Where there before this was added. Thanks @TheAlgorythm. Doing a release with this now.

**Pull request merged**
