### PR TITLE
Fix grammar?/typo in READMY.md

### PR DESCRIPTION
**Pull request by samarth-ramesh**
conscience != conscious
Ref. https://www.vocabulary.com/articles/chooseyourwords/conscious-conscience/

### CODE REVIEW

**Comment by grooverdan** [comment]
typo in READMY ? just joking.

Thanks for the fix and the reference. Much appreciate using the right terms when explaining things.

**Comment by samarth-ramesh** [comment]
> typo in READMY ? just joking.

Oh god. i should look before I hit ctrl+enter again
Thanks for pointing it out

**Comment by iangilfillan** [comment]
Note that the fix is also wrong. 
consience -> conscience

**Comment by grooverdan** [comment]
c8b1d5c finally :-)

**Pull request merged**
