### PR TITLE
Release 2024q4 part 1

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Comment by jgb** [comment]
Hello, when will 11.4.4 be available on docker hub? It's been a few days since the merge and I still see 11.4.3 as the latest version. Thanks!

**Comment by grooverdan** [comment]
Because I removed 11.5, the there wasn't a branch to make `latest` without making 11.4, a (unsupported) downgrade the `latest`, so I'm waiting  a few more days until 11.6/7 come out and do them all at once. Sorry for the delay.

**Comment by grooverdan** [comment]
temporary version https://github.com/MariaDB/mariadb-docker/pkgs/container/mariadb/300198909?tag=11.4.4-noble

**Comment by grooverdan** [comment]
https://github.com/docker-library/official-images/pull/17905 when merged will build/push them.

**Pull request merged**
